spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.profiles.active=dsv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.mongodb.uri=${MONGO_URL}

server.port=8080

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

api.security.google.client-id=${GOOGLE_CLIENT_ID}
api.security.admin.emails=${ADMIN_EMAILS}
api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${JWT_ISSUER}
api.security.token.expiration-hours=2